# Generated by Django 6.1 on 2026-08-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_profile_date_of_birth_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pic/"),
        ),
    ]
