# Generated by Django 5.2.17 on 2026-09-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_id_alter_profile_id_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('campus_life', 'Campus Life'), ('achievement', 'Achievement'), ('event', 'Event'), ('announcement', 'Announcement'), ('question', 'Question'), ('lost_found', 'Lost & Found'), ('help', 'Help / Discussion'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
